### ISSUE TITLE
improvements to homepage

### ISSUE THREAD

**Issue by arshiamufti** [StarConKW/starconuw.github.io#109]
- remove the "venue" heading
- update the speakers heading to mention vaidehi and that other speakers will be announced when the CFP closes
- remove "policies" (we can add it back in closer to the date of event)
- move "starcon 2018" to be closer to the bottom (maybe right before "where can i get updates")

**Comment by evykassirer** [comment]
hmm for policies and venue - could be useful for potential speakers to see if we're inclusive for them?
