### ISSUE TITLE
List of attributes for abstract isn't rendered correctly

### ISSUE THREAD

**Issue by jdm** [StarConKW/starconuw.github.io#115]
In https://starcon.io/cfp/ the resulting markup is:
```html
    <ul>
      <li>The title of your talk.</li>
      <li>What the audience can expect to learn from your talk.
 	- Why you think the topic of the talk is interesting, important, cool etc.</li>
    </ul>
```
The markdown in cfp.md looks ok, so I'm not sure what's going wrong.

**Comment by arshiamufti** [comment]
weiiiird.

**Comment by arshiamufti** [comment]
uh looks like the third point was indented with a tab character *and* a space but it didn't look like it in the UI. (if that makes sense). See patch.

**Comment by arshiamufti** [comment]
well, that fixed it, thanks for pointing this out!

**Comment by evykassirer** [comment]
weeeird 

thanks both of you!
