### ISSUE TITLE
Update "Who's Organizing This?"

### ISSUE THREAD

**Issue by arshiamufti** [StarConKW/starconuw.github.io#96]

**Comment by evykassirer** [comment]
idk if we should list out EVERYONE's names now? I could add another sentence "x y z have joined our team to help run 2019" since they're also not wics folks (and then keep first sentence the same) but idk if that sounds bad

**Comment by annalorimer** [comment]
I think listing everyone's name is a nice thing to do (see !!con's site).

**Comment by evykassirer** [comment]
That sounds good to me! I can do when I get back or let Chirag or someone else do beforehand if you think it's more urgent
